__title__ = "rsyncer"
__description__ = "rsync wrapper for python."
__url__ = "https://github.com/lfreist/PyRsync"
__version__ = "0.0.1"
__author__ = "Leon Freist"
__author_email__ = "freist@informatik.uni-freiburg.de"
__copyright__ = "Copyright 2022 Leon Freist"
